### ISSUE TITLE
solr.backup.dir=... [solrcore.properties] not set through docker-compose GLOBAL_ALL_solr.backup.dir

### ISSUE THREAD

**Issue by Ranecdev** [xenit-eu/docker-solr#58]
Since Alfresco Search Services 2.*:
Solr will ignore the location parameter in the backup command (`solr/<shard-name>/replication?command=backup&location=/opt/alfresco-search-services/data/solr6Backup&numberToKeep=3`) due to a security vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2020-13941).
So there is a new property in the solrcore.properties file https://github.com/Alfresco/SearchServices/blob/master/search-services/alfresco-search/src/main/resources/solr/instance/templates/rerank/conf/solrcore.properties#L242
However when I try to set this variable with - GLOBAL_ALL_solr.backup.dir=/opt/alfresco-search-services/data/solr6Backup
It is not recorded in solrcore.properties. The value remains commented out

**Comment by anghelutar** [comment]
The problem appears because of the space in solr.backup.dir in solrcore.properties, after the comment. An easy fix is adapting the replace lines in 92-init-solr.sh to optionally allow for spaces before properties:

+       sed -i "s#^\s*\($1\s*=\s*\).*\$#\1$2#" $3
+       sed -i "s#^\#\s*\($1\s*=\s*\).*\$#\1$2#" $3

It is to be seen if shell manipulation is robust enough for the init script. In my experience with docker-solr, there were not often issues related to this.
